import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import { PriceRuleForm } from "@/components/admin/price-rule-form";
import { DeletePriceRuleButton } from "@/components/admin/delete-price-rule-button";
export const dynamic = "force-dynamic";
const days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"];
export default async function PricingPage() { const s = await getServerSession(authOptions); if (!s) redirect("/admin/login"); const [rules, courts] = await Promise.all([db.courtPriceRule.findMany({ include: { court: true }, orderBy: { createdAt: "desc" } }), db.court.findMany({ where: { isActive: true }, select: { id: true, name: true } })]); return <div><p className="text-sm font-bold uppercase tracking-[.18em] text-primary">Operasional</p><h1 className="mt-2 text-3xl font-extrabold">Aturan harga</h1><p className="mt-2 text-muted">Tarif khusus per lapangan, hari, dan jam.</p><PriceRuleForm courts={courts} /><div className="mt-6 grid gap-3">{rules.length === 0 ? <div className="rounded-xl border border-dashed border-border p-10 text-center text-muted">Belum ada aturan harga khusus. Harga dasar lapangan masih digunakan.</div> : rules.map((rule) => <article key={rule.id} className="flex flex-wrap items-end justify-between gap-4 rounded-xl border border-border bg-surface p-5"><div><p className="font-extrabold">{rule.court.name}</p><p className="mt-1 text-sm text-muted">{rule.dayOfWeek === null ? "Semua hari" : days[rule.dayOfWeek]} · {rule.startsAt}–{rule.endsAt}</p><p className="mt-3 text-xl font-extrabold text-primary">Rp{Number(rule.hourlyRate).toLocaleString("id-ID")} / jam</p></div><DeletePriceRuleButton id={rule.id} /></article>)}</div></div>; }
