"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const input = "h-11 rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-primary";
export function PromoForm() {
  const router = useRouter(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/admin/promos", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: data.get("name"), code: data.get("code"), type: data.get("type"), value: Number(data.get("value")), startsAt: new Date(`${data.get("startsAt")}T00:00:00+07:00`), endsAt: new Date(`${data.get("endsAt")}T23:59:59+07:00`), isActive: data.get("isActive") === "on" }) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Promo gagal dibuat."); setSaving(false); return; } event.currentTarget.reset(); setSaving(false); router.refresh(); }
  return <form onSubmit={submit} className="mt-6 grid gap-4 rounded-xl border border-border bg-surface p-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold sm:col-span-2">Nama promo<input required name="name" className={input} placeholder="Promo Kemerdekaan" /></label><label className="grid gap-2 text-sm font-bold">Kode promo<input required name="code" className={`${input} uppercase`} placeholder="AGUSTUS20" /></label><label className="grid gap-2 text-sm font-bold">Jenis diskon<select name="type" className={input}><option value="PERCENTAGE">Persentase (%)</option><option value="FIXED_AMOUNT">Nominal (Rp)</option></select></label><label className="grid gap-2 text-sm font-bold">Nilai diskon<input required name="value" type="number" min="1" className={input} /></label><label className="grid gap-2 text-sm font-bold">Mulai<input required name="startsAt" type="date" className={input} /></label><label className="grid gap-2 text-sm font-bold">Berakhir<input required name="endsAt" type="date" className={input} /></label><label className="flex items-center gap-3 text-sm font-bold sm:col-span-2"><input name="isActive" type="checkbox" defaultChecked className="size-4 accent-primary" />Aktifkan promo</label>{error ? <p className="text-sm text-red-300 sm:col-span-2">{error}</p> : null}<button disabled={saving} className="rounded-lg bg-primary px-5 py-3 font-extrabold text-primary-foreground disabled:opacity-70 sm:col-span-2">{saving ? "Menyimpan..." : "Buat promo"}</button></form>;
}
